name: e2e tests

on: workflow_dispatch

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.11.1
      - name: Install packages
        run: yarn install

      - name: run component set
        run: yarn dev
