name: Publish bundle.js to production

on: 
  workflow_dispatch:
  branches:
    - production
  paths-ignore:
  - 'CHANGELOG.md'
  - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      with: 
      node-version: 16.11.1
      - name: Install packages
        run: yarn install

    name: build
      run: yarn build
  
    - name: bundle
    run: yarn bundle

    - name: upload
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_EDGE }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_EDGE }}
    run: yarn upload bundle
    - name: upload aws
      env:
        AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_AWS }}
        AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_AWS }}
    run: yarn upload bundle
    - name: upload bench
      env:
        AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_BENCH }}
        AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_BENCH }}
    run: yarn upload bundle
    - name: upload ca3
      env:
        AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_CA3 }}
        AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_CA3 }}
    run: yarn upload bundle
    - name: upload cc2
      env:
        AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_CC2 }}
        AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_CC2 }}
    run: yarn upload bundle
    - name: upload nh1816
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_NH1816 }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_NH1816 }}
    run: yarn upload bundle
  - name: upload nl3
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_NL3 }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_NL3 }}
    run: yarn upload bundle
  - name: upload nl4
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_NL4 }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_NL4 }}
    run: yarn upload bundle
  - name: upload nrfem
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_NRFEM }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_NRFEM }}
    run: yarn upload bundle
  - name: upload us2
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_US2 }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_US2 }}
    run: yarn upload bundle
  - name: upload vabi
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_VABI }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_VABI }}
  run: yarn upload bundle
  - name: upload vvv
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_VVV }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_VVV }}
    run: yarn upload bundle
  - name: upload frasers
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_FRASERS }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_FRASERS }}
    run: yarn upload bundle
  - name: upload pfl
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_PFL }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_PFL }}
    run: yarn upload bundle
  - name: upload Holygrow
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_HOLYGROW }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_HOLYGROW }}
    run: yarn upload bundle
  - name: upload NL6
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_NL6 }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_NL6 }}
    run: yarn upload bundle
  - name: upload police
    env:
      AZURE_BLOB_ACCOUNT: ${{ secrets.AZURE_BLOB_ACCOUNT_POLICE }}
      AZURE_BLOB_ACCOUNT_KEY: ${{ secrets.AZURE_BLOB_ACCOUNT_KEY_POLICE }}
    run: yarn upload bundle